### ISSUE TITLE
BUG | Not posting to EOS

### ISSUE THREAD

**Issue by IFTGFTC** [louisgv/nemo#29]
## To Reproduce

1. Record catch
2. click post to EOS
3. Cursor turns into Circle with cross through it and application stalls

## Logs or Screenshots
<details><summary>Expand for Contents</summary>
<p>

```

SUPER_LONG_LOG__

```

</p>
</details>

**Comment by louisgv** [comment]
This happened due to a recent update in IPFS js API. I will need to update nemo's IPFS usage and it should be able to send to EOS.
